### ISSUE TITLE
@OAuth2RestOperationsAutowired causes just a BeanCreationException

### ISSUE THREAD

**Issue by ePaul** [zalando-stups/spring-boot-zalando-stups-tokens#3]
Maybe I'm using it wrong, but there isn't much documentation.

From [@jbellmann's comment](https://github.com/zalando-stups/stups-spring-oauth2-support/issues/33#issuecomment-215215806) I did build this:

``` java
@Configuration
public class ProducerConfiguration {

    private static final String PRODUCER_TOKEN_NAME = "producer";

    @Value("${PRODUCER_EVENTS_URI}")
    private String producerEventsURI;

    @OAuth2RestOperationsAutowired(PRODUCER_TOKEN_NAME)
    private RestOperations template;
}
```

In my application-dev.yml I have the following setup:

``` yaml
tokens:
    token-configuration-list:
        - tokenId: producer
          scopes:
              - uid
              - producer.event_stream.read
        - tokenId: nakadi
          scopes: nakadi.event_stream.write


spring:
  oauth2:
    resource:
      tokenInfoUri: https://info.services.auth.zalando.com/oauth2/tokeninfo
```

Starting the app (with a dummy producer URL in an environment variable) gives me just a BeanCreationException:

> Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.web.client.RestOperations] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.zalando.stups.tokens.annotation.OAuth2RestOperationsAutowired(value=producer)}

This doesn't change whether or not I have also `stups-spring-oauth2-client` in my Maven dependencies.
